/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 6.382727793574192, 7.22207654789282, 6.443176549247354 };
const float ei_classifier_anom_mean[3] = { 7.7164647823279315, 7.92763619371914, 6.585669160486861 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { 0.7131804823875427, 0.6851761937141418, -0.22032004594802856 }, 0.4270524159884119 },
	{ ( float[3] ) { 1.4394800662994385, 0.6007325053215027, 1.3754796981811523 }, 0.6454611596353397 },
	{ ( float[3] ) { 1.851479411125183, 1.6166205406188965, 1.648188829421997 }, 0.5296442072905961 },
	{ ( float[3] ) { -0.953827977180481, -0.9429367780685425, -0.8625978231430054 }, 0.3208434602289115 },
	{ ( float[3] ) { -0.7931078672409058, -0.8822089433670044, -0.7599692344665527 }, 0.2207301813329852 },
	{ ( float[3] ) { -0.7568914294242859, -0.6155659556388855, -0.5945749282836914 }, 0.28357541087064536 },
	{ ( float[3] ) { 0.40802907943725586, -0.06205792352557182, 0.10391701757907867 }, 0.4791415318122923 },
	{ ( float[3] ) { -0.954985499382019, -0.8612751364707947, -0.6858105063438416 }, 0.2680586180877386 },
	{ ( float[3] ) { 0.5802266597747803, 0.6635947823524475, 1.8958879709243774 }, 0.39685196216995877 },
	{ ( float[3] ) { 0.8408267498016357, -0.2970860004425049, -0.4023948311805725 }, 0.7705345330588711 },
	{ ( float[3] ) { 1.0605533123016357, 1.6671574115753174, 1.6399738788604736 }, 0.4713574974960349 },
	{ ( float[3] ) { 0.44533511996269226, 1.8255552053451538, 0.7273263931274414 }, 0.5031946411337906 },
	{ ( float[3] ) { 0.8416407108306885, 1.1129266023635864, 1.1658695936203003 }, 0.48159479179464093 },
	{ ( float[3] ) { 0.5108559131622314, 0.713995099067688, 1.0154041051864624 }, 0.402256450636199 },
	{ ( float[3] ) { 0.3851284384727478, 0.7888437509536743, 3.154196262359619 }, 0.3327725942505527 },
	{ ( float[3] ) { 0.008686704561114311, 0.2435709536075592, 0.9705755114555359 }, 0.5538720574287751 },
	{ ( float[3] ) { 0.24590229988098145, 0.34217506647109985, -0.5273085832595825 }, 0.4242264444086768 },
	{ ( float[3] ) { 1.0250707864761353, 0.4060767590999603, 0.597058117389679 }, 0.45671099381932895 },
	{ ( float[3] ) { 1.4450560808181763, 1.0597563982009888, 1.973541498184204 }, 0.47609569569031807 },
	{ ( float[3] ) { 1.3151804208755493, 1.3276336193084717, -0.04736807197332382 }, 0.8853394019699662 },
	{ ( float[3] ) { -0.5356543660163879, -0.8169505000114441, -0.7535496354103088 }, 0.468450849432788 },
	{ ( float[3] ) { 2.7017226219177246, 0.8020458221435547, 0.2377452850341797 }, 0.6965736298846309 },
	{ ( float[3] ) { -0.12203823029994965, -0.4131116271018982, -0.05945959687232971 }, 0.5246818056709766 },
	{ ( float[3] ) { 0.6399720311164856, 0.08814919739961624, 1.4363136291503906 }, 0.4489506925344999 },
	{ ( float[3] ) { 1.2172309160232544, 0.5243732333183289, 2.2173385620117188 }, 0.5703247650277029 },
	{ ( float[3] ) { 2.0199458599090576, 1.068618893623352, 1.1540428400039673 }, 0.49584157014805386 },
	{ ( float[3] ) { 0.5616167187690735, 3.089108943939209, 0.4161107838153839 }, 0.40240336143927696 },
	{ ( float[3] ) { 1.4723786115646362, 0.7550169825553894, -0.17703360319137573 }, 0.6925599091830963 },
	{ ( float[3] ) { -0.8030943870544434, 0.32034632563591003, -0.6213220953941345 }, 0.24962880304042964 },
	{ ( float[3] ) { 0.5287688970565796, 1.536192536354065, 2.1701178550720215 }, 0.890623332627427 },
	{ ( float[3] ) { 0.215915247797966, 0.49014347791671753, -0.02273685112595558 }, 0.5112165585376459 },
	{ ( float[3] ) { 0.7771493196487427, 2.5733776092529297, 2.124875783920288 }, 0.44099512865411755 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
