/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1.5592073524023229, 1.1896380676930502, 1.393097303931757 };
const float ei_classifier_anom_mean[3] = { 2.0498542460551, 3.0185718820240326, 1.4336213681444967 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.8545678853988647, -1.6250323057174683, 1.7960965633392334 }, 0.9019914553929025 },
	{ ( float[3] ) { -0.05203332006931305, 0.4082561135292053, -0.17534774541854858 }, 0.7523507981400818 },
	{ ( float[3] ) { 1.2147294282913208, -1.3170030117034912, -0.6266751885414124 }, 0.7065483643189376 },
	{ ( float[3] ) { -0.03018062561750412, 0.6528313755989075, -0.021100908517837524 }, 0.7161548548336687 },
	{ ( float[3] ) { -0.8544003963470459, 0.2981506586074829, -0.27886950969696045 }, 0.43737102466870786 },
	{ ( float[3] ) { -0.45943620800971985, 0.4648025631904602, -0.02870357409119606 }, 0.7273230835919755 },
	{ ( float[3] ) { -0.35820019245147705, 0.29806947708129883, -0.31214892864227295 }, 0.41190266452739305 },
	{ ( float[3] ) { -0.36692583560943604, 0.825075089931488, -0.2691584825515747 }, 0.9987652069877723 },
	{ ( float[3] ) { -0.6305282115936279, 0.20701655745506287, -0.2767479717731476 }, 0.3884145784401411 },
	{ ( float[3] ) { 0.2998410165309906, 0.9446108341217041, -0.015577754937112331 }, 1.3486553212457095 },
	{ ( float[3] ) { 1.01993727684021, -1.9467417001724243, -0.5636201500892639 }, 0.6070611666769824 },
	{ ( float[3] ) { -0.7232846617698669, 0.5429484248161316, -0.5254265069961548 }, 0.6741259415299058 },
	{ ( float[3] ) { -0.30165958404541016, 0.001784149557352066, -0.06459634006023407 }, 1.354885962849071 },
	{ ( float[3] ) { 1.9521470069885254, -0.9717034697532654, -0.3604232966899872 }, 0.9824670984909883 },
	{ ( float[3] ) { 8.865165710449219, 8.34709358215332, 9.961383819580078 }, 0.7415786479796939 },
	{ ( float[3] ) { 2.5454561710357666, -0.4777989387512207, 0.16134113073349 }, 1.2327025737989423 },
	{ ( float[3] ) { 1.0391325950622559, -1.0361549854278564, 0.22332663834095 }, 1.0944006826950727 },
	{ ( float[3] ) { 4.083775997161865, 1.9962031841278076, 3.4989566802978516 }, 1.278138008145885 },
	{ ( float[3] ) { 1.5081737041473389, -1.5069786310195923, -0.25976917147636414 }, 0.9768549526314564 },
	{ ( float[3] ) { 0.022797895595431328, -0.19281375408172607, 4.727053642272949 }, 0.7066595050178259 },
	{ ( float[3] ) { 0.9261124730110168, 4.2957282066345215, 2.8132951259613037 }, 1.6852652762229394 },
	{ ( float[3] ) { 2.80133056640625, 2.3117947578430176, 1.39723539352417 }, 1.2465548045586519 },
	{ ( float[3] ) { 4.284168720245361, -0.10084748268127441, 3.8902885913848877 }, 2.4975559802632237 },
	{ ( float[3] ) { 1.0785499811172485, 6.01137638092041, 4.585209369659424 }, 1.954726636452757 },
	{ ( float[3] ) { 0.7808256149291992, -0.17084144055843353, 2.508821964263916 }, 1.7106187881786883 },
	{ ( float[3] ) { 1.8479584455490112, 0.2053932547569275, 1.3887102603912354 }, 1.1349389869806046 },
	{ ( float[3] ) { 2.932450532913208, 0.39159634709358215, 2.5176842212677 }, 0.8139489707955057 },
	{ ( float[3] ) { -0.2365257441997528, -1.048080325126648, 3.49987530708313 }, 0.9324344132802105 },
	{ ( float[3] ) { 5.627723693847656, 5.164463520050049, 6.235511302947998 }, 1.444480927043124 },
	{ ( float[3] ) { 2.2186505794525146, 0.3809478282928467, 8.960026741027832 }, 1.4807244019813568 },
	{ ( float[3] ) { 4.928837776184082, -0.36171403527259827, 1.6122263669967651 }, 1.5489996673840696 },
	{ ( float[3] ) { 3.255169153213501, 9.177655220031738, 11.463896751403809 }, 1.9521786348766905 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
